version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      
  node-docker-app:
    build: .
    # ports:
    #   - "8000:8000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # environment:
    #   - PORT=8000
    env_file:
      - ./.env
    # to run mongodb container first, use depends_on
    depends_on:
      - mongodb
  
  mongodb: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rathink4
      - MONGO_INITDB_ROOT_PASSWORD=mongodb_pass3
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    

volumes:
  mongo-db: